- name: password.yaml # To retrieve jenkins password from instance 
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Ansible copy file to remote server # We need the Jenkins Admin password for first login, this is stored here, we will fetch it to ~/devop$

      fetch:

        src: /var/lib/jenkins/secrets/initialAdminPassword

        dest: ./

        flat: yes

        mode: 0744 # Permissions on file can be non-strict, since the password is used only once anyway.






