- name: post-install-rpm.yaml # Configuring service and firewall in RPM Distros.
  hosts: ec2_instances
  become: yes
  tasks: 
    - name: Script for further Jenkins configuration needed on RPM repo's. Firewall and Service activation.
      script: post-install.sh # This script is used to bootstrap the jenkins service, and allow it past the firewall. for RPM only. Debian is autoconfigured.
      become: yes # become root
      when: ansible_facts['os_family'] == "RedHat" # Only for RedHat distro's

    - name: Ansible copy file to remote server
      
      fetch:
       
        src: /var/lib/jenkins/secrets/initialAdminPassword 

        dest: ./

        flat: yes

        mode: 0744 
